VERSION_NUMBER = "0.0.0"

JENKINS_GRADLE_NAME = "opleidingen_maven"

JSPM_GITHUB_AUTH_TOKEN = env.JSPM_GITHUB_AUTH_TOKEN
TEST_SERVER_USERNAME = env.TEST_SERVER_USERNAME
TEST_SERVER_URL = env.TEST_SERVER_URL

try {
    stage("pre-steps") {
        node("linux && docker") {
            cleanWorkspace()
            cloneProject()
            buildMavenImage()
        }
    }
    stage("build") {
        node("linux && docker") {
            maven("test -Dmaven.test.failure.ignore=true --settings .maven/settings_jenkins_vdab.xml")
            archiveAllTestResults()
        }
    }
    stage("deploy") {
        node("linux && docker") {
            maven("versions:set -DnewVersion=${VERSION_NUMBER} -DskipTests --settings .maven/settings_jenkins_vdab.xml")
            maven("clean install -DskipFrontendPlugin -DskipTests --settings .maven/settings_jenkins_vdab.xml")
        }
    }
    stage("deploy to Test") {
        milestone 1
        askForDeploy('Deploy to Test?')
        milestone 2
        node("linux && docker") {
            stopServer(TEST_SERVER_USERNAME, TEST_SERVER_URL)
            copyJar(TEST_SERVER_USERNAME, TEST_SERVER_URL)
            startServer(TEST_SERVER_USERNAME, TEST_SERVER_URL)
        }
    }
} catch (org.jenkinsci.plugins.workflow.steps.FlowInterruptedException exception) {
    return
}

def cleanWorkspace() {
    sh "mkdir ~/.tmp/${env.BUILD_TAG}"
    try {
        sh "mv opleidingen-server/src/main/resources/ui/node_modules ~/.tmp/${env.BUILD_TAG}/node_modules"
        sh "mv opleidingen-server/src/main/resources/ui/src/jspm_packages ~/.tmp/${env.BUILD_TAG}/jspm_packages"
        sh "mv opleidingen-server/src/main/resources/ui/yarn.lock ~/.tmp/${env.BUILD_TAG}/yarn.lock"
    } catch (err) {
    }
    sh "rm -rf *"
    try {
        sh "mkdir -p opleidingen-server/src/main/resources/ui/src"
        sh "mv ~/.tmp/${env.BUILD_TAG}/node_modules/ opleidingen-server/src/main/resources/ui/node_modules"
        sh "mv ~/.tmp/${env.BUILD_TAG}/jspm_packages/ opleidingen-server/src/main/resources/ui/src/jspm_packages"
        sh "mv ~/.tmp/${env.BUILD_TAG}/yarn.lock opleidingen-server/src/main/resources/ui/yarn.lock"
    } catch (err) {
    }
    sh "rm -rf ~/.tmp/${env.BUILD_TAG}"
}

def cloneProject() {
    checkout scm
}

def buildMavenImage() {
    sh "docker build --build-arg JSPM_GITHUB_AUTH_TOKEN=${JSPM_GITHUB_AUTH_TOKEN} -t opleidingen/maven opleidingen-server/ "
}

def archiveAllTestResults() {
    step([$class: "JUnitResultArchiver", testResults: "opleidingen-server/target/surefire-reports/TEST-*.xml"])
}

def askForDeploy(message) {
    timeout(time: 28, unit: 'DAYS') {
        input message: "${message}"
    }
}

def copyJar(username, host) {
    sh "scp opleidingen-server/target/opleidingen-server-${VERSION_NUMBER}.jar ${username}@${host}:opleidingen/server/opleidingen-server.jar"
}

def startServer(username, host) {
    sh "ssh ${username}@${host} opleidingen/server/startOpleidigenServer.sh"
}

def stopServer(username, host) {
    try {
        sh "ssh ${username}@${host} opleidingen/server/stopOpleidigenServer.sh"
    } catch (err) {
        printError(err)
    }
}

def maven(task) {
    def mavenName = "${JENKINS_GRADLE_NAME}.${VERSION_NUMBER}"

    try {
        startMavenContainer(mavenName)
        execMaven(mavenName, task)
    } catch (err) {
        printError(err)
        currentBuild.result = "FAILURE"
    } finally {
        removeContainer(mavenName)
    }
}

def startMavenContainer(mavenName) {
    def currentDir = pwd()
    killContainer(mavenName)
    sh "docker run -t -d --name ${mavenName} -v $currentDir/opleidingen-server:/usr/src/opleidingen -v /usr/maven/.m2/repository:/usr/maven/.m2/repository opleidingen/maven bash"
}
def execMaven(mavenName, task) {
    sh "docker exec ${mavenName} mvn  ${task}"
}

def killContainer(name) {
    try {
        sh "docker rm -vf ${name}"
    } catch (err) {
    }
}

def removeContainer(name) {
    try {
        sh "docker stop ${name}"
    } catch (err) {
    }
    try {
        sh "docker rm -v ${name}"
    } catch (err) {
    }
}

def printError(error) {
    println "******************************* WORKFLOW ERROR *******************************"
    println "${error}"
    println "******************************************************************************"
}